# Generated by Django 5.0.2 on 2026-02-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_source_file_storage', models.CharField(choices=[('local', 'Local Server'), ('cloud', 'Cloud Server (S3)'), ('nas', 'NAS Server')], default='nas', help_text='Default storage location for source files.', max_length=10)),
                ('nas_root_path', models.CharField(default='/mnt/StudioOps', help_text='Root path for NAS storage (e.g., /mnt/StudioOps).', max_length=255)),
                ('s3_bucket_name', models.CharField(blank=True, help_text='AWS S3 bucket name for cloud storage.', max_length=255, null=True)),
                ('s3_region', models.CharField(blank=True, help_text='AWS S3 region (e.g., us-east-1).', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Storage Setting',
                'verbose_name_plural': 'Storage Settings',
            },
        ),
    ]
