# Generated by Django 5.0.2 on 2026-02-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_storagesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagesetting',
            name='default_final_file_storage',
            field=models.CharField(choices=[('local', 'Local Server'), ('cloud', 'Cloud Server (S3)'), ('nas', 'NAS Server')], default='cloud', help_text='Default storage location for final deliverable files.', max_length=10),
        ),
        migrations.AddField(
            model_name='storagesetting',
            name='default_preview_file_storage',
            field=models.CharField(choices=[('local', 'Local Server'), ('cloud', 'Cloud Server (S3)'), ('nas', 'NAS Server')], default='local', help_text='Default storage location for preview files.', max_length=10),
        ),
    ]
