# Generated by Django 5.0.2 on 2026-02-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_assigned_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstageelement',
            name='status_notes',
            field=models.TextField(blank=True, help_text='Reason for hold, block, or other status changes.'),
        ),
        migrations.AddField(
            model_name='taskstatuslog',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
