# Generated by Django 5.0.2 on 2025-12-29 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstageelement',
            name='contribution_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stageelementversion',
            name='rollback_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.stageelementversion'),
        ),
        migrations.CreateModel(
            name='ProjectAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('psd', 'Photoshop'), ('ai', 'Illustrator'), ('ae', 'After Effects'), ('pr', 'Premiere Pro'), ('video', 'Video'), ('image', 'Image'), ('other', 'Other')], max_length=20)),
                ('asset_role', models.CharField(choices=[('source', 'Source File'), ('preview', 'Preview Render'), ('final', 'Final Deliverable')], max_length=20)),
                ('file', models.FileField(upload_to='project_assets/')),
                ('storage_location', models.CharField(choices=[('local', 'Local Server'), ('cloud', 'Cloud Server')], default='local', max_length=10)),
                ('client_review', models.BooleanField(default=False)),
                ('version_number', models.PositiveIntegerField(editable=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='project.projectstageelement')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('element', 'version_number', 'client_review')},
            },
        ),
        migrations.CreateModel(
            name='ClientReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_notes', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='project.projectasset')),
            ],
        ),
        migrations.CreateModel(
            name='VersionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('rolled_back', 'Rolled Back')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='project.stageelementversion')),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectAttachment',
        ),
    ]
