# Generated by Django 5.0.2 on 2025-12-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_projectstageelement_contribution_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectasset',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
