# Generated by Django 5.0.2 on 2026-02-04 07:47

import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_package_alter_projectasset_file_packageitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstageelement',
            name='initial_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectasset',
            name='file',
            field=models.FileField(upload_to=project.models.ProjectAsset.project_asset_upload_path),
        ),
    ]
