# Generated by Django 5.0.2 on 2026-02-05 21:56

import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_projectstageelement_initial_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttaskassignment',
            name='initial_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectasset',
            name='file',
            field=models.FileField(upload_to=project.models.ProjectAsset.project_asset_upload_path),
        ),
    ]
