# Generated by Django 5.0.2 on 2026-02-05 22:12

import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_alter_projectasset_file_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projecttaskassignment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='projectasset',
            name='file',
            field=models.FileField(upload_to=project.models.ProjectAsset.project_asset_upload_path),
        ),
    ]
