# Generated by Django 5.0.2 on 2026-02-05 22:15

import project.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_alter_projecttaskassignment_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectasset',
            name='file',
            field=models.FileField(upload_to=project.models.ProjectAsset.project_asset_upload_path),
        ),
        migrations.AlterUniqueTogether(
            name='projecttaskassignment',
            unique_together={('task', 'user')},
        ),
    ]
