# Generated by Django 5.0.2 on 2026-02-08 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_leadsource_service_and_more'),
        ('project', '0019_taskcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='service_type',
        ),
        migrations.AddField(
            model_name='project',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='project.package'),
        ),
        migrations.AddField(
            model_name='project',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='Sales.service'),
        ),
    ]
