# Generated by Django 5.0.2 on 2026-02-08 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_remove_project_service_type_project_package_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderStructureTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A unique name for the folder structure template.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of this template.')),
                ('structure', models.JSONField(help_text='JSON representation of the folder structure tree.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='folder_structure_template',
            field=models.ForeignKey(blank=True, help_text='Optional: The folder structure template to use for this project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='project.folderstructuretemplate'),
        ),
    ]
