# Generated by Django 5.2.8 on 2025-12-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clients_address_clients_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
