# Generated by Django 5.2.8 on 2025-12-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clients_account_number_clients_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Hold', 'On Hold'), ('Archived', 'Archived')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='clients',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
