# Generated by Django 5.0.2 on 2026-02-20 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0002_initial'),
        ('project', '0003_storagesetting_default_final_file_storage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='folder_structure_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='project.folderstructuretemplate'),
        ),
        migrations.AddField(
            model_name='service',
            name='workflow_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='project.projectstagetemplate'),
        ),
    ]
