# Generated by Django 5.0.2 on 2026-02-20 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_service_folder_structure_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='workflow_template',
        ),
    ]
