# Generated by Django 5.0.2 on 2026-02-20 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0004_remove_service_workflow_template'),
        ('project', '0003_storagesetting_default_final_file_storage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project.package'),
        ),
    ]
